"use client";

import { useTranslations } from "next-intl";
import { Info } from "lucide-react";

interface AiDisclaimerProps {
  /** Optional override for the disclaimer text */
  message?: string;
}

/**
 * Standardized AI disclaimer component for wizard phases that use AI generation.
 * Blue info box with Info icon, following the Phase 6 pattern.
 *
 * Used in: DestinationGuideWizard (Phase 5), Phase6Wizard
 * Spec ref: SPEC-PROD-016 (AI content transparency)
 */
export function AiDisclaimer({ message }: AiDisclaimerProps) {
  const t = useTranslations("expedition");

  const text = message ?? t("aiDisclaimer", {
    fallback: "Content generated by AI. Review and adjust as needed for your trip.",
  });

  return (
    <div
      className="flex items-start gap-3 rounded-lg border border-atlas-info-container bg-atlas-info-container p-4 dark:border-atlas-info/40 dark:bg-atlas-info-container/20"
      role="note"
      data-testid="ai-disclaimer"
    >
      <Info
        className="mt-0.5 h-5 w-5 flex-shrink-0 text-atlas-info"
        aria-hidden="true"
      />
      <p className="text-sm text-atlas-info dark:text-atlas-info">
        {text}
      </p>
    </div>
  );
}
