"use client";

import { useTranslations } from "next-intl";
import { Info } from "lucide-react";

interface AiDisclaimerProps {
  /** Optional override for the disclaimer text */
  message?: string;
}

/**
 * Standardized AI disclaimer component for wizard phases that use AI generation.
 * Blue info box with Info icon, following the Phase 6 pattern.
 *
 * Used in: DestinationGuideWizard (Phase 5), Phase6Wizard
 * Spec ref: SPEC-PROD-016 (AI content transparency)
 */
export function AiDisclaimer({ message }: AiDisclaimerProps) {
  const t = useTranslations("expedition");

  const text = message ?? t("aiDisclaimer", {
    fallback: "Content generated by AI. Review and adjust as needed for your trip.",
  });

  return (
    <div
      className="flex items-start gap-3 rounded-lg border border-blue-200 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-950/30"
      role="note"
      data-testid="ai-disclaimer"
    >
      <Info
        className="mt-0.5 h-5 w-5 flex-shrink-0 text-blue-500"
        aria-hidden="true"
      />
      <p className="text-sm text-blue-700 dark:text-blue-300">
        {text}
      </p>
    </div>
  );
}
